export { default as CreateExamScreen } from './CreateExamScreen'
export { default as CreateQuestionScreen } from './CreateQuestionScreen'
export { default as CompleteExamScreen } from './CompleteExamScreen'
export { default as MarkExamScreen } from './MarkExamScreen'
export { default as ListExamsScreen } from './ListExamsScreen'
export { default as WatchCorrectionExamScreen } from './WatchCorrectionExamScreen'
